apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: sgmap
spec:
  version: {{ .TagName }}
  homepage: https://github.com/naka-gawa/kubectl-sgmap
  shortDescription: "Visualize security group per pod."
  description: |
    A kubectl plugin to visualize security group per pod.
    This plugin provides a command to generate a security group map for pods in a Kubernetes cluster.
  platforms:
  - selector:
      matchLabels:
        os: darwin
        arch: arm64
    files:
      - from: "kubectl-sgmap"
        to: "."
      - from: "LICENSE"
        to: "."
    {{addURIAndSha "https://github.com/naka-gawa/kubectl-sgmap/releases/download/{{ .TagName }}/kubectl-sgmap_Darwin_arm64.tar.gz" .TagName }}
    bin: "./kubectl-sgmap"
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    files:
      - from: "kubectl-sgmap"
        to: "."
      - from: "LICENSE"
        to: "."
    {{addURIAndSha "https://github.com/naka-gawa/kubectl-sgmap/releases/download/{{ .TagName }}/kubectl-sgmap_Darwin_x86_64.tar.gz" .TagName }}
    bin: "./kubectl-sgmap"
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    files:
      - from: "kubectl-sgmap"
        to: "."
      - from: "LICENSE"
        to: "."
    {{addURIAndSha "https://github.com/naka-gawa/kubectl-sgmap/releases/download/{{ .TagName }}/kubectl-sgmap_Linux_x86_64.tar.gz" .TagName }}
    bin: "./kubectl-sgmap"
  - selector:
      matchLabels:
        os: linux
        arch: arm64
    files:
      - from: "kubectl-sgmap"
        to: "."
      - from: "LICENSE"
        to: "."
    {{addURIAndSha "https://github.com/naka-gawa/kubectl-sgmap/releases/download/{{ .TagName }}/kubectl-sgmap_Linux_arm64.tar.gz" .TagName }}
    bin: "./kubectl-sgmap"
