apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: sgmap
spec:
  version: {{ .TagName }}
  homepage: https://github.com/naka-gawa/kubectl-sgmap
  shortDescription: "Visualize security group per pod."
  description: |
    A kubectl plugin to visualize security group per pod.
    This plugin provides a command to generate a security group map for pods in a Kubernetes cluster.
  platforms:
    - selector:
        matchLabels:
          os: darwin
          arch: arm64
      files:
        - from: "kubectl-sgmap"
          to: "."
        - from: "LICENSE"
          to: "."
      bin: "./kubectl-sgmap"
      {{addURIAndSha "https://github.com/naka-gawa/kubectl-sgmap/releases/download/{{ .TagName }}/kubectl-sgmap_Darwin_arm64.tar.gz" .TagName }}
    - selector:
        matchLabels:
          os: darwin
          arch: amd64
      sha256: fea8adfa9f9ad8c264c055c02cafe3e894c0dc86f4816975eb29c0a6d223862e
      files:
        - from: "kubectl-sgmap"
          to: "."
        - from: "LICENSE"
          to: "."
      bin: "./kubectl-sgmap"
      {{addURIAndSha "https://github.com/naka-gawa/kubectl-sgmap/releases/download/{{ .TagName }}/kubectl-sgmap_Darwin_x86_64.tar.gz" .TagName }}
    - selector:
        matchLabels:
          os: linux
          arch: amd64
      sha256: c8c793dbf244c2c90f46464263a37625192271cc2695b4a77f93b7c77143677e
      files:
        - from: "kubectl-sgmap"
          to: "."
        - from: "LICENSE"
          to: "."
      bin: "./kubectl-sgmap"
      {{addURIAndSha "https://github.com/naka-gawa/kubectl-sgmap/releases/download/{{ .TagName }}/kubectl-sgmap_Linux_x86_64.tar.gz" .TagName }}
    - selector:
        matchLabels:
          os: linux
          arch: arm64
      sha256: a1ce98a1d0ac0296fe7c6ae031e5d761b7f8809584491f46150a557ee4ae1313
      files:
        - from: "kubectl-sgmap"
          to: "."
        - from: "LICENSE"
          to: "."
      bin: "./kubectl-sgmap"
      {{addURIAndSha "https://github.com/naka-gawa/kubectl-sgmap/releases/download/{{ .TagName }}/kubectl-sgmap_Linux_arm64.tar.gz" .TagName }}
