name: test

on:
  pull_request:
    branches: ["main"]
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Set up Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: "go.mod"
        env:
          TAR_OPTIONS: "--skip-old-files"

      - name: Ensure Dependencies
        run: go mod tidy

      - name: Build and Test
        run: make build
